/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCardDialog: typeof import('./src/components/dialog/AddCardDialog.vue')['default']
    BaseCard: typeof import('./src/components/card/BaseCard.vue')['default']
    BookmarkCard: typeof import('./src/components/card/BookmarkCard.vue')['default']
    BookmarkForm: typeof import('./src/components/form/BookmarkForm.vue')['default']
    CardInformation: typeof import('./src/components/card/CardInformation.vue')['default']
    ChooseBookmark: typeof import('./src/components/form/ChooseBookmark.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CountdownCard: typeof import('./src/components/card/CountdownCard.vue')['default']
    CountdownForm: typeof import('./src/components/form/CountdownForm.vue')['default']
    EditCardDataDialog: typeof import('./src/components/dialog/EditCardDataDialog.vue')['default']
    IconChooseDialog: typeof import('./src/components/dialog/IconChooseDialog.vue')['default']
    LocalIconData: typeof import('./src/components/icon/LocalIconData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3ConfigForm: typeof import('./src/components/form/S3ConfigForm.vue')['default']
    ShowS3FileListDialog: typeof import('./src/components/dialog/ShowS3FileListDialog.vue')['default']
    Status: typeof import('./src/components/status/index.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStickyItem: typeof import('tdesign-vue-next')['StickyItem']
    TStickyTool: typeof import('tdesign-vue-next')['StickyTool']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    WeatherCard: typeof import('./src/components/card/WeatherCard.vue')['default']
    WeatherForm: typeof import('./src/components/form/WeatherForm.vue')['default']
  }
}
