import { CardInformationData, CardType, SwiperData } from '@/types';
import { IconStoreType } from '@/types/icon';
import * as IconConstants from '@/constants/icon';

// 默认书签数据
export const defaultBookmarkData: SwiperData[] = [
  {
    id: 'FfYSPo1jH21SVrsGK2Edr',
    data: [
      {
        id: 'RWNafLzih1wI_YslKzM15',
        name: 'DeepSeek',
        type: 0,
        url: 'https://chat.deepseek.com/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_DEEPSEEK_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_DEEPSEEK_ICON],
        bgColor: '#4D6BFF',
        placeholder: false,
        position: { x: 0, y: 0, w: 1, h: 2 },
      },
      {
        name: 'Kimi',
        type: 0,
        placeholder: false,
        position: { x: 1, y: 0, w: 1, h: 1 },
        url: 'https://www.kimi.com/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_KIMI_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_KIMI_ICON],
        bgColor: 'rgba(0, 0, 0, 1)',
        id: 'ZTlv7O9bo5-L2PZk4XbcQ',
      },
      {
        name: '百度贴吧',
        type: 0,
        placeholder: false,
        position: { x: 2, y: 0, w: 2, h: 1 },
        url: 'https://tieba.baidu.com/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_TIEBA_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_TIEBA_ICON],
        bgColor: 'rgba(38, 111, 232, 1)',
        id: 'RB1aDlBx5vlknu-Y8GvFl',
      },

      {
        id: 'rV5RXj6IdkwlP78VFC3xZ',
        name: '抖音',
        type: 0,
        url: 'https://www.douyin.com',
        desc: '抖音短视频',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_DOUYIN_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_DOUYIN_ICON],
        bgColor: 'rgba(0, 0, 0, 1)',
        placeholder: false,
        position: { x: 4, y: 0, w: 1, h: 1 },
      },
      {
        id: 'iOINQfdbsmU8FwLJxCzAa',
        name: '网易云音乐',
        type: 0,
        url: 'https://music.163.com/#/discover/recommend/taste',
        desc: '网易云音乐',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_NETEASE_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_NETEASE_ICON],
        bgColor: '#C20C0B',
        placeholder: false,
        position: { x: 5, y: 0, w: 1, h: 1 },
      },
      {
        id: '1XlY31ARpiTjJrQpcFCHQ',
        name: '哔哩哔哩',
        type: 0,
        url: 'https://www.bilibili.com/',
        desc: '哔哩哔哩弹幕网',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_BILIBILI_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_BILIBILI_ICON],
        bgColor: '#FA7298',
        placeholder: false,
        position: { x: 6, y: 0, w: 1, h: 1 },
      },
      {
        name: '今日头条',
        type: 0,
        placeholder: false,
        position: {
          x: 7,
          y: 0,
          w: 1,
          h: 1,
        },
        url: 'https://www.toutiao.com/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_TOUTIAO_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_TOUTIAO_ICON],
        bgColor: 'rgb(255, 255, 255, 1)',
        id: 'WSUiSaE6Z2aC0DexAFqH0',
      },

      {
        name: '微博',
        type: 0,
        placeholder: false,
        position: {
          x: 8,
          y: 0,
          w: 1,
          h: 1,
        },
        url: 'https://weibo.com/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_WEIBO_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_WEIBO_ICON],
        bgColor: '#D52B2A',
        id: 'RWNs_KSo1Yg1SI8NMV3E_',
      },

      {
        name: '知乎',
        type: 0,
        placeholder: false,
        position: {
          x: 9,
          y: 0,
          w: 1,
          h: 1,
        },
        url: 'https://zhihu.com/',
        desc: 'B乎',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_ZHIHU_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_ZHIHU_ICON],
        bgColor: '#1872F5',
        id: 'RWNs_KSo1Yg1SI8NMV4E_',
      },
      {
        name: '淘宝',
        type: 0,
        placeholder: false,
        position: {
          x: 10,
          y: 0,
          w: 1,
          h: 1,
        },
        url: 'https://www.taobao.com/',
        desc: '淘宝网',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_TAOBAO_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_TAOBAO_ICON],
        bgColor: '#FF5000',
        id: 'ZnH0VzS8ZRlNOD5yDPkt6',
      },
      {
        name: '京东',
        type: 0,
        placeholder: false,
        position: {
          x: 11,
          y: 0,
          w: 1,
          h: 1,
        },
        url: 'https://www.jd.com/',
        desc: 'JD购物商城',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_JD_ICON,
        icons: [IconConstants.DEFAULT_BOOKMARK_JD_ICON,],
        bgColor: '#EB4730',
        id: 'RWNs_KSo1Yg1SI8NMV1E_',
      },

      {
        type: 0,
        name: 'Github',
        placeholder: false,
        position: { x: 3, y: 1, w: 2, h: 1 },
        url: 'https://github.com/',
        desc: 'Github',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_GITHUB_ICON,
        icons: [
          IconConstants.DEFAULT_BOOKMARK_GITHUB_ICON,
        ],
        bgColor: 'rgba(0, 0, 0, 1)',
        id: 'Is_VKyL6oibhxYJYS2jmG',
      },
      {
        id: 'hZQZZSDh7bevFNBTTD2Z',
        name: '豆包',
        type: 0,
        url: 'https://www.doubao.com/chat/',
        desc: '豆包AI',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_DOUBAO_ICON,
        icons: [
          IconConstants.DEFAULT_BOOKMARK_DOUBAO_ICON,
        ],
        bgColor: '#CAE3ff',
        placeholder: false,
        position: { x: 1, y: 1, w: 1, h: 1 },
      },
      {
        name: 'Qwen',
        type: 0,
        placeholder: false,
        position: {
          x: 2,
          y: 1,
          w: 1,
          h: 1,
        },
        url: 'https://chat.qwen.ai/',
        desc: '',
        iconType: 0,
        icon: IconConstants.DEFAULT_BOOKMARK_QWEN_ICON,
        icons: [
          IconConstants.DEFAULT_BOOKMARK_QWEN_ICON,
        ],
        bgColor: 'rgba(38, 111, 232, 1)',
        id: 'RWNs_KSo1Yg1SI8NMV2E_',
      },
    ],
  },
  {
    id: 'pRoxoyHqbEDKxEcJh8bzR',
    data: [],
  },
  {
    id: 'Os4xtEQBIc0xypXM8cRsC',
    data: [],
  },
  {
    id: 'XezRjgtDpO5WNgQto514W',
    data: [],
  },
];



/**
 * 所有可用的卡片组件配置
 */
export const ALL_COMPONENT_CARD: ReadonlyArray<CardInformationData> = [
  {
    title: '书签',
    type: CardType.BOOKMARK,
    image: new URL('@/assets/card/bookmark.svg', import.meta.url).href,
    desc: '保存链接网页，方便快速访问常用网站，还能分类整理网页，提升浏览效率',
  },
  {
    title: '天气',
    type: CardType.WEATHER,
    image: new URL('@/assets/card/weather.svg', import.meta.url).href,
    desc: '显示当前城市天气状况，包括温度、湿度和未来几天天气预报.',
  },
  {
    title: '倒计时',
    type: CardType.COUNTDOWN,
    image: new URL('@/assets/card/countdown.svg', import.meta.url).href,
    desc: '倒计时功能，用于提示重要事件,节日,任务的剩余时间.',
  },
] as const;

// 默认的倒计时背景图片列表
export const DEFAULT_COUNTDOWN_BACKGROUND_LIST = [
  new URL('@/assets/countdown/001.webp', import.meta.url).href,
  new URL('@/assets/countdown/002.webp', import.meta.url).href,
  new URL('@/assets/countdown/003.webp', import.meta.url).href,
  new URL('@/assets/countdown/004.webp', import.meta.url).href,
];
